name = "ninja-zenshin-tracker"
compatibility_date = "2026-07-05"
pages_build_output_dir = "."

[[d1_databases]]
binding = "NINJA_D1"
database_name = "ninja-zenshin-db"
database_id = "81bfcffd-28d7-457a-965c-6749e3cac8e9"
